# Site settings
title: VirtualLab
baseurl: 
host:

# Build settings
# 'github-pages' gem should automatically pull in the right markdown processor

# As Github pages build support, our site will use 'kramdown' for markdown rendering
markdown: kramdown
# Turn on recognition of GitHub Flavored Markdown 
kramdown:
  input: GFM 

include: ["_pages"]
