# Site settings
title: The Virtual Lab
baseurl: 
host:

# Build settings
# 'github-pages' gem should automatically pull in the right markdown processor

# As Github pages build support, our site will use 'kramdown' for markdown rendering
markdown: kramdown
# Turn on recognition of GitHub Flavored Markdown 
kramdown:
  input: GFM
  hard_wrap: false

include: ["_pages"]
